import { ValidationType } from "../_types/formGen_types";

export const formFieldsToExcludeInTable = ["emailVerified", "address", "createdAt", "deletedAt"];

// Example usage
export const formFieldsForEditUpdate: ValidationType = {
  id: {
    id: 345,
    name: "id",
    label: "ID",
    type: "number",
    required: true,
    pattern: null,
    options: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
  name: {
    id: 578,
    name: "name",
    label: "Name",
    type: "text",
    required: true,
    min: 3,
    max: 50,
    pattern: null,
    options: null,
    enum: null,
    error: null,
  },
  email: {
    id: 8667,
    name: "email",
    label: "Email",
    type: "text",
    required: true,
    pattern: {
      value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
      message: "Invalid email address",
      type: "text",
    },

    options: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
  address: {
    id: 10987,
    name: "address",
    label: "Address",
    type: "multiline",
    required: true,
    pattern: null,
    options: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
  logo: {
    id: 592,
    name: "logo",
    label: "Logo",
    type: "imageupload",
    options: [
      { value: "1", label: "active" },
      { value: "0", label: "not active" },
    ],
    required: true,
    pattern: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
  active: {
    id: 7775,
    name: "active",
    label: "Active",
    type: "radio",
    options: [
      { value: "1", label: "active" },
      { value: "0", label: "not active" },
    ],
    required: true,
    pattern: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },

  test1: {
    id: 886231,
    name: "test1",
    label: "Test1",
    type: "checkbox",
    required: true,
    options: [
      { value: "check1", label: "check1-label" },
      { value: "check2", label: "check2-label" },
      { value: "check3", label: "check3-label" },
    ],
    pattern: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
  daterange: {
    id: 900037,
    name: "daterange1",
    label: "Date Range",
    type: "daterange",
    required: true,
    options: null,
    pattern: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
  daterange2: {
    id: 7878686,
    name: "daterange2",
    label: "Date Range v2 selector",
    type: "daterangev2",
    required: true,
    options: null,
    pattern: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
  paymentOptions: {
    id: 9191,
    name: "paymentOptions",
    label: "Payment Options",
    type: "select",
    options: [
      { value: "Credit Card", label: "Credit Card" },
      { value: "PayPal", label: "PayPal" },
      { value: "Bank Transfer", label: "Bank Transfer" },
    ],
    required: true,
    pattern: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
  contacts: {
    id: 897660,
    name: "contacts",
    label: "Contacts",
    type: "text",
    required: true,
    pattern: null,
    options: null,
    enum: null,
    min: null,
    max: null,
    error: null,
  },
};
