// import { RecipeDataProps } from "@/types/recipeTypes";
// import { is } from "cypress/types/bluebird";
// import { extend } from "cypress/types/lodash";
// import Decimal from "decimal.js";

// export const data: RecipeDataProps = {
//   uuid: "1234567890",
//   name: "My Recipe name that could be very very long",
//   desc: "Thinly sliced beef with a pepper sauce and roasted veg",

//   portions: [
//     { id: 1234, qty_g: 265, order: 1 },
//     { id: 1235, qty_g: 350, order: 2 },
//   ],

//   // portions: [265, 350],
//   packagingCostsId: [
//     { pid: 1234, rule: 5 },
//     { pid: 1235, rule: 6 },
//   ],
//   // packagingCostsId: { 265: 5, 350: 6 },
//   otherCostsId: [
//     { pid: 1234, rule: 4 },
//     { pid: 1235, rule: 3 },
//   ],
//   // otherCostsId: { 265: 3, 350: 4 },
//   markupId: [
//     { pid: 1234, rule: 1 },
//     { pid: 1235, rule: 2 },
//   ],
//   // markupId: { 265: 3, 350: 8 },
//   vatRulesId: [
//     { pid: 1234, rule: 1 },
//     { pid: 1235, rule: 2 },
//   ],
//   // vatRulesId: [2, 2],

//   components: [
//     {
//       name: "Master - FC Chicken Breast Novation Cooked",
//       uuid: "77442",
//       order: 1,
//       recipeId: "77442-666",
//       version: "22_mar_2024_12h34_WK_2",

//       type: "sub",
//       // parentId: null,
//       ingredient_id: 666,

//       portions: [
//         { id: 1234, qty_g: 90 },
//         { id: 1235, qty_g: 120 },
//       ],
//       yield: new Decimal(0.71),
//       nutri_per_100g: [
//         { name: "kcal", value_per_100g: 2000, unit: "kcal" },
//         { name: "kj", value_per_100g: 4000, unit: "kcal" },
//         { name: "protein", value_per_100g: 7, unit: "g" },
//         { name: "fat", value_per_100g: 1.5, unit: "g" },
//         { name: "saturated fat", value_per_100g: 0.7, unit: "g" },
//         { name: "monounsaturate fat", value_per_100g: 0.5, unit: "g" },
//         { name: "Polyunsaturate fat", value_per_100g: 0.2, unit: "g" },
//         { name: "trans fats", value_per_100g: 0, unit: "g" },
//         { name: "omega-3", value_per_100g: 0.1, unit: "g" },
//         { name: "omega-6", value_per_100g: 0.05, unit: "g" },
//         { name: "omega-9", value_per_100g: 0.1, unit: "g" },
//         { name: "net carbohydrate", value_per_100g: 6, unit: "g" },
//         { name: "total carbohydrate", value_per_100g: 9, unit: "g" },
//         { name: "starch", value_per_100g: 1.3, unit: "g" },
//         { name: "total sugars", value_per_100g: 5, unit: "g" },
//         { name: "added sugar", value_per_100g: 0.2, unit: "g" },
//         { name: "artificial sugar", value_per_100g: 0, unit: "g" },
//         { name: "fibre", value_per_100g: 2, unit: "g" },
//         { name: "sodium", value_per_100g: 0.5, unit: "g (#mg)" },
//         { name: "salt", value_per_100g: 1, unit: "g (#mg)" },
//       ],
//     },
//     {
//       name: "Master - FC Rosemary Gravy",
//       uuid: "101235",
//       order: 2,
//       recipeId: "101235-666",
//       version: "22_mar_2024_12h34_WK_2",

//       type: "sub",
//       // parentId: null,
//       ingredient_id: null,

//       portions: [
//         { id: 1234, qty_g: 40 },
//         { id: 1235, qty_g: 50 },
//       ],
//       yield: new Decimal(0.86),
//       nutri_per_100g: [
//         { name: "kcal", value_per_100g: 2000, unit: "kcal" },
//         { name: "kj", value_per_100g: 4000, unit: "kcal" },
//         { name: "protein", value_per_100g: 7, unit: "g" },
//         { name: "fat", value_per_100g: 1.5, unit: "g" },
//         { name: "saturated fat", value_per_100g: 0.7, unit: "g" },
//         { name: "monounsaturate fat", value_per_100g: 0.5, unit: "g" },
//         { name: "Polyunsaturate fat", value_per_100g: 0.2, unit: "g" },
//         { name: "trans fats", value_per_100g: 0, unit: "g" },
//         { name: "omega-3", value_per_100g: 0.1, unit: "g" },
//         { name: "omega-6", value_per_100g: 0.05, unit: "g" },
//         { name: "omega-9", value_per_100g: 0.1, unit: "g" },
//         { name: "net carbohydrate", value_per_100g: 6, unit: "g" },
//         { name: "total carbohydrate", value_per_100g: 9, unit: "g" },
//         { name: "starch", value_per_100g: 1.3, unit: "g" },
//         { name: "total sugars", value_per_100g: 5, unit: "g" },
//         { name: "added sugar", value_per_100g: 0.2, unit: "g" },
//         { name: "artificial sugar", value_per_100g: 0, unit: "g" },
//         { name: "fibre", value_per_100g: 2, unit: "g" },
//         { name: "sodium", value_per_100g: 0.5, unit: "g (#mg)" },
//         { name: "salt", value_per_100g: 1, unit: "g (#mg)" },
//       ],
//     },
//     {
//       name: "Dukkah Roasted Butternut with Feta",
//       uuid: "322",
//       recipeId: "322-666",
//       order: 3,
//       version: "22_mar_2024_12h34_WK_2",

//       type: "sub",
//       // parentId: null,
//       ingredient_id: null,

//       portions: [
//         { id: 1234, qty_g: 70 },
//         { id: 1235, qty_g: 90 },
//       ],
//       yield: new Decimal(1),
//       nutri_per_100g: [
//         { name: "kcal", value_per_100g: 2000, unit: "kcal" },
//         { name: "kj", value_per_100g: 4000, unit: "kcal" },
//         { name: "protein", value_per_100g: 7, unit: "g" },
//         { name: "fat", value_per_100g: 1.5, unit: "g" },
//         { name: "saturated fat", value_per_100g: 0.7, unit: "g" },
//         { name: "monounsaturate fat", value_per_100g: 0.5, unit: "g" },
//         { name: "Polyunsaturate fat", value_per_100g: 0.2, unit: "g" },
//         { name: "trans fats", value_per_100g: 0, unit: "g" },
//         { name: "omega-3", value_per_100g: 0.1, unit: "g" },
//         { name: "omega-6", value_per_100g: 0.05, unit: "g" },
//         { name: "omega-9", value_per_100g: 0.1, unit: "g" },
//         { name: "net carbohydrate", value_per_100g: 6, unit: "g" },
//         { name: "total carbohydrate", value_per_100g: 9, unit: "g" },
//         { name: "starch", value_per_100g: 1.3, unit: "g" },
//         { name: "total sugars", value_per_100g: 5, unit: "g" },
//         { name: "added sugar", value_per_100g: 0.2, unit: "g" },
//         { name: "artificial sugar", value_per_100g: 0, unit: "g" },
//         { name: "fibre", value_per_100g: 2, unit: "g" },
//         { name: "sodium", value_per_100g: 0.5, unit: "g (#mg)" },
//         { name: "salt", value_per_100g: 1, unit: "g (#mg)" },
//       ],
//     },
//     {
//       name: "Spinach Fritters",
//       uuid: "98747",
//       recipeId: "98747-666",
//       order: 4,
//       version: "22_mar_2024_12h34_WK_2",

//       type: "sub",
//       // parentId: null,
//       ingredient_id: null,

//       portions: [
//         { id: 1234, qty_g: 45 },
//         { id: 1235, qty_g: 60 },
//       ],
//       yield: new Decimal(0.89),
//       nutri_per_100g: [
//         { name: "kcal", value_per_100g: 2000, unit: "kcal" },
//         { name: "kj", value_per_100g: 4000, unit: "kcal" },
//         { name: "protein", value_per_100g: 7, unit: "g" },
//         { name: "fat", value_per_100g: 1.5, unit: "g" },
//         { name: "saturated fat", value_per_100g: 0.7, unit: "g" },
//         { name: "monounsaturate fat", value_per_100g: 0.5, unit: "g" },
//         { name: "Polyunsaturate fat", value_per_100g: 0.2, unit: "g" },
//         { name: "trans fats", value_per_100g: 0, unit: "g" },
//         { name: "omega-3", value_per_100g: 0.1, unit: "g" },
//         { name: "omega-6", value_per_100g: 0.05, unit: "g" },
//         { name: "omega-9", value_per_100g: 0.1, unit: "g" },
//         { name: "net carbohydrate", value_per_100g: 6, unit: "g" },
//         { name: "total carbohydrate", value_per_100g: 9, unit: "g" },
//         { name: "starch", value_per_100g: 1.3, unit: "g" },
//         { name: "total sugars", value_per_100g: 5, unit: "g" },
//         { name: "added sugar", value_per_100g: 0.2, unit: "g" },
//         { name: "artificial sugar", value_per_100g: 0, unit: "g" },
//         { name: "fibre", value_per_100g: 2, unit: "g" },
//         { name: "sodium", value_per_100g: 0.5, unit: "g (#mg)" },
//         { name: "salt", value_per_100g: 1, unit: "g (#mg)" },
//       ],
//     },
//     {
//       name: "Master - FC Rosemary Gravy",
//       uuid: "1012399",
//       recipeId: "101235-666",
//       order: 5,
//       version: "22_mar_2024_12h34_WK_2",

//       type: "sub",
//       // parentId: null,
//       ingredient_id: null,

//       portions: [
//         { id: 1234, qty_g: 20 },
//         { id: 1235, qty_g: 30 },
//       ],
//       yield: new Decimal(0.86),
//       nutri_per_100g: [
//         { name: "kcal", value_per_100g: 2000, unit: "kcal" },
//         { name: "kj", value_per_100g: 4000, unit: "kcal" },
//         { name: "protein", value_per_100g: 7, unit: "g" },
//         { name: "fat", value_per_100g: 1.5, unit: "g" },
//         { name: "saturated fat", value_per_100g: 0.7, unit: "g" },
//         { name: "monounsaturate fat", value_per_100g: 0.5, unit: "g" },
//         { name: "Polyunsaturate fat", value_per_100g: 0.2, unit: "g" },
//         { name: "trans fats", value_per_100g: 0, unit: "g" },
//         { name: "omega-3", value_per_100g: 0.1, unit: "g" },
//         { name: "omega-6", value_per_100g: 0.05, unit: "g" },
//         { name: "omega-9", value_per_100g: 0.1, unit: "g" },
//         { name: "net carbohydrate", value_per_100g: 6, unit: "g" },
//         { name: "total carbohydrate", value_per_100g: 9, unit: "g" },
//         { name: "starch", value_per_100g: 1.3, unit: "g" },
//         { name: "total sugars", value_per_100g: 5, unit: "g" },
//         { name: "added sugar", value_per_100g: 0.2, unit: "g" },
//         { name: "artificial sugar", value_per_100g: 0, unit: "g" },
//         { name: "fibre", value_per_100g: 2, unit: "g" },
//         { name: "sodium", value_per_100g: 0.5, unit: "g (#mg)" },
//         { name: "salt", value_per_100g: 1, unit: "g (#mg)" },
//       ],
//     },
//   ],

//   recipes: [
//     {
//       name: "Master - FC Chicken Breast Novation Cooked",
//       uuid: "77442-666",
//       costPer1000: 43.7,
//       brand: { name: "fitchef", id: 3452, logoSrc: "" },
//       customer: { name: "emperors", id: 8667, logoSrc: "" },
//       method: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
//           Ipsum has been the industrys standard dummy text ever since the 1500s, when an
//           unknown printer took a galley of type and scrambled it to make a type specimen
//           book. It has survived not only five centuries, but also the leap into electronic
//           typesetting, remaining essentially unchanged. It was popularised in the 1960s with`,
//       recipeDetail: [
//         {
//           uuid: "111",
//           ingredId: 666,
//           ingredName: "Do not overcook chicken. Remove Chicken from bone while warm",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           //  pro: g kg ton mL L = qty
//           // home g kg mL L = home_qty
//           //
//           //
//           uuid: "222",
//           ingredId: 666,
//           ingredName: "Chicken Breast Marination (Novation)", // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,

//           qty: 10000,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 65.22235,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333",
//           ingredId: 666,
//           ingredName: "Rosemary - Dried Fine",
//           qty: 100, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 88.03,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "444",
//           ingredId: 666,
//           ingredName: "Thyme Fitchef Seasoning",
//           qty: 50, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 61.89625,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555",
//           ingredId: 666,
//           ingredName: "Remove Chicken from bone while warm. Try avoid cartilage or bone",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//       ],
//     },
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     {
//       name: "Master - FC Rosemary Gravy",
//       uuid: "101235-666",
//       costPer1000: 43.7,
//       brand: { name: "fitchef", id: 3452, logoSrc: "" },
//       customer: { name: "emperors", id: 8667, logoSrc: "" },
//       method: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
//           Ipsum has been the industrys standard dummy text ever since the 1500s, when an
//           unknown printer took a galley of type and scrambled it to make a type specimen
//           book. It has survived not only five centuries, but also the leap into electronic
//           typesetting, remaining essentially unchanged. It was popularised in the 1960s with`,
//       recipeDetail: [
//         {
//           uuid: "1111",
//           ingredId: 666,
//           ingredName: "Sautee onions (light brown)",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "2222",
//           ingredId: 666,
//           ingredName: "Onion - White Fresh Whole",
//           qty: 0.2, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 9.5,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "3333",
//           ingredId: 666,
//           ingredName: "Water",
//           qty: 0.035, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 0.7,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "4444",
//           ingredId: 666,
//           ingredName: "STEP 2 - Add, Simmer and Blend Fine",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "5555",
//           ingredId: 666,
//           ingredName: "Garlic - Fresh Whole",
//           qty: 0.0267073779399365, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 160,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "6666",
//           ingredId: 666,
//           ingredName: "Water",
//           qty: 0.356708130019699, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 0.7,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "7777",
//           ingredId: 666,
//           ingredName: "Rosemary - Dried Fine",
//           qty: 0.00310347048751908, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 88.03,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "8888",
//           ingredId: 666,
//           ingredName: "Oreganum - Dried",
//           qty: 0.00195122395908212, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 48.9,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "9999",
//           ingredId: 666,
//           ingredName: "Salt",
//           qty: 0.00662073704004071, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 42.93,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "101010",
//           ingredId: 666,
//           ingredName: "Pepper - Black Fine",
//           qty: 0.000827592130005088, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 185,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "111111",
//           ingredId: 666,
//           ingredName: "Lemon - Juice",
//           qty: 0.00393106261752417, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 30.7692307692308,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "121212",
//           ingredId: 666,
//           ingredName: "Purity W",
//           qty: 0.025, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 95.82,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "131313",
//           ingredId: 666,
//           ingredName: "Chicken Stock Granules",
//           qty: 0.0479879142436758, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 44.35,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "141414",
//           ingredId: 666,
//           ingredName: "Add Cream and remove from heat",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "151515",
//           ingredId: 666,
//           ingredName: "Cream (Dairy) - Fresh",
//           qty: 0.1, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 57.35,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "161616",
//           ingredId: 666,
//           ingredName: "Milk Low Fat",
//           qty: 0.1, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 13.38,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//       ],
//     },
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     {
//       name: "Dukkah Roasted Butternut with Feta",
//       uuid: "322-666",
//       costPer1000: 43.7,
//       brand: { name: "fitchef", id: 3452, logoSrc: "" },
//       customer: { name: "emperors", id: 8667, logoSrc: "" },
//       method: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
//           Ipsum has been the industrys standard dummy text ever since the 1500s, when an
//           unknown printer took a galley of type and scrambled it to make a type specimen
//           book. It has survived not only five centuries, but also the leap into electronic
//           typesetting, remaining essentially unchanged. It was popularised in the 1960s with`,
//       recipeDetail: [
//         {
//           uuid: "222-666",
//           ingredId: 666,
//           ingredName: " Dukkah Roasted Butternut with Feta",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",

//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//           subRecipeId: "555-666",
//         },
//         {
//           uuid: "333-666",
//           ingredId: 666,
//           ingredName: "Dukkah Roasted Butternut ",
//           qty: 2.24, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "sub",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 32.8200027777778,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: "4567789",
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "444-666",
//           ingredId: 666,
//           ingredName: "Feta",
//           qty: 0.2, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 115.71,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-666",
//           ingredId: 666,
//           ingredName: "Pumpkin Seeds",
//           qty: 0.05, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 125.9,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "666-666",
//           ingredId: 666,
//           ingredName: "Coriander ",
//           qty: 0.01, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 145,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//       ],
//     },
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     {
//       name: "Spinach Fritters",
//       uuid: "98747-666",
//       costPer1000: 43.7,
//       brand: { name: "fitchef", id: 3452, logoSrc: "" },
//       customer: { name: "emperors", id: 8667, logoSrc: "" },
//       method: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
//       Ipsum has been the industrys standard dummy text ever since the 1500s, when an
//       unknown printer took a galley of type and scrambled it to make a type specimen
//       book. It has survived not only five centuries, but also the leap into electronic
//       typesetting, remaining essentially unchanged. It was popularised in the 1960s with`,
//       recipeDetail: [
//         {
//           uuid: "333-111",
//           ingredId: 666,
//           ingredName: "Spinach ",
//           qty: 0.45, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 52.2,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-222",
//           ingredId: 666,
//           ingredName: "Onion",
//           qty: 0.02, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 12.9,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-333",
//           ingredId: 666,
//           ingredName: "Mozzarella",
//           qty: 0.05, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 94,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-444",
//           ingredId: 666,
//           ingredName: "Feta Low Fat",
//           qty: 0.035, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 115.71,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-555",
//           ingredId: 666,
//           ingredName: "Sweet Potato Mash",
//           qty: 0.15, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 71.1298461850649,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-666",
//           ingredId: 666,
//           ingredName: "Eggs",
//           qty: 0.15, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 52.4,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-777",
//           ingredId: 666,
//           ingredName: "Blended Oats",
//           qty: 0.04, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 37.1764705882353,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-888",
//           ingredId: 666,
//           ingredName: "Thyme Fitchef Seasoning",
//           qty: 0.005, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 61.89625,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-999",
//           ingredId: 666,
//           ingredName: "Paprika",
//           qty: 0.0005, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 52,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "333-1010",
//           ingredId: 666,
//           ingredName: "Coconut Oil Spray",
//           qty: 0.005, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 139.1,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//       ],
//     },

//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     //   ______________________________________________________
//     {
//       uuid: "4619766-666",
//       name: "Master - FC Rosemary Gravy",
//       costPer1000: 43.7,
//       brand: { name: "fitchef", id: 3452, logoSrc: "" },
//       customer: { name: "emperors", id: 8667, logoSrc: "" },
//       method: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
//       Ipsum has been the industrys standard dummy text ever since the 1500s, when an
//       unknown printer took a galley of type and scrambled it to make a type specimen
//       book. It has survived not only five centuries, but also the leap into electronic
//       typesetting, remaining essentially unchanged. It was popularised in the 1960s with`,
//       recipeDetail: [
//         {
//           uuid: "555 -111",
//           ingredId: 666,
//           ingredName: "Sautee onions (light brown)",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-222",
//           ingredId: 666,
//           ingredName: "Onion - White Fresh Whole",
//           qty: 0.2, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 9.5,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-333",
//           ingredId: 666,
//           ingredName: "Water",
//           qty: 0.035, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 0.7,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-444",
//           ingredId: 666,
//           ingredName: "STEP 2 - Add, Simmer and Blend Fine",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-555",
//           ingredId: 666,
//           ingredName: "Garlic - Fresh Whole",
//           qty: 0.0267073779399365, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 160,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-666",
//           ingredId: 666,
//           ingredName: "Water",
//           qty: 0.356708130019699, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 0.7,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-777",
//           ingredId: 666,
//           ingredName: "Rosemary - Dried Fine",
//           qty: 0.00310347048751908, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 88.03,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-888",
//           ingredId: 666,
//           ingredName: "Oreganum - Dried",
//           qty: 0.00195122395908212, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 48.9,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-999",
//           ingredId: 666,
//           ingredName: "Salt",
//           qty: 0.00662073704004071, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 42.93,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-1010",
//           ingredId: 666,
//           ingredName: "Pepper - Black Fine",
//           qty: 0.000827592130005088, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 185,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-1111",
//           ingredId: 666,
//           ingredName: "Lemon - Juice",
//           qty: 0.00393106261752417, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 30.7692307692308,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-1212",
//           ingredId: 666,
//           ingredName: "Purity W",
//           qty: 0.025, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 95.82,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-1313",
//           ingredId: 666,
//           ingredName: "Chicken Stock Granules",
//           qty: 0.0479879142436758, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 44.35,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-1414",
//           ingredId: 666,
//           ingredName: "Add Cream and remove from heat",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-1515",
//           ingredId: 666,
//           ingredName: "Cream (Dairy) - Fresh",
//           qty: 0.1, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 57.35,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "555-1616",
//           ingredId: 666,
//           ingredName: "Milk Low Fat",
//           qty: 0.1, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 13.38,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//       ],
//     },
//     //  ______________________________________________________
//     //  ______________________________________________________
//     //  ______________________________________________________
//     //  ______________________________________________________
//     //  ______________________________________________________
//     {
//       uuid: "4567789",
//       name: "Dukkah Roasted Butternut",
//       costPer1000: 23.5,
//       brand: { name: "fitchef", id: 3452, logoSrc: "" },
//       customer: { name: "emperors", id: 8667, logoSrc: "" },
//       method: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
//           Ipsum has been the industrys standard dummy text ever since the 1500s, when an
//           unknown printer took a galley of type and scrambled it to make a type specimen
//           book. It has survived not only five centuries, but also the leap into electronic
//           typesetting, remaining essentially unchanged. It was popularised in the 1960s with`,
//       recipeDetail: [
//         {
//           uuid: "777-111",
//           ingredId: 666,
//           ingredName: "Dukkah Roasted Butternut",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "777-222",
//           ingredId: 666,
//           ingredName: "Butternut ",
//           qty: 1, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 12.5,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "777-333",
//           ingredId: 666,
//           ingredName: "Dukkah Seasoning",
//           qty: 0.06, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "sub",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 271.208375,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",

//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//           subRecipeId: "8765788-111",
//         },
//         {
//           uuid: "777-444",
//           ingredId: 666,
//           ingredName: "Coconut Oil Spray",
//           qty: 0.005, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 139.1,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "777-667",
//           ingredId: 666,
//           ingredName: "Honey",
//           qty: 0.1, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 0.7,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//       ],
//     },

//     //  ______________________________________________________
//     //  ______________________________________________________
//     //  ______________________________________________________
//     //  ______________________________________________________
//     //  ______________________________________________________
//     //  ______________________________________________________
//     {
//       uuid: "8765788-111",
//       name: "Dukah spices",
//       costPer1000: 23.5,
//       brand: { name: "fitchef", id: 3452, logoSrc: "" },
//       customer: { name: "emperors", id: 8667, logoSrc: "" },
//       method: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
//           Ipsum has been the industrys standard dummy text ever since the 1500s, when an
//           unknown printer took a galley of type and scrambled it to make a type specimen
//           book. It has survived not only five centuries, but also the leap into electronic
//           typesetting, remaining essentially unchanged. It was popularised in the 1960s with`,
//       recipeDetail: [
//         {
//           uuid: "888-111",
//           ingredId: 666,
//           ingredName: "Dukkah Spice",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "step",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-222",
//           ingredId: 666,
//           ingredName: "Hazelnuts",
//           qty: 0.08, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 275.9,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-333",
//           ingredId: 666,
//           ingredName: "Almonds",
//           qty: 0.03, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 157.4,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-444",
//           ingredId: 666,
//           ingredName: "Sesame Seeds",
//           qty: 0.02, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 68,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-555",
//           ingredId: 666,
//           ingredName: "Pistachios",
//           qty: 0.03, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 477.6,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-666",
//           ingredId: 666,
//           ingredName: "Fennel Seeds",
//           qty: 0.005, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 39.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-777",
//           ingredId: 666,
//           ingredName: "Cumin",
//           qty: 0.003, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 158.25,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-999",
//           ingredId: 666,
//           ingredName: "Corriander ",
//           qty: 0.003, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 49.02,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-101011",
//           ingredId: 666,
//           ingredName: "Cayenne Pepper",
//           qty: 0.001, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 48.3,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-10111",
//           ingredId: 666,
//           ingredName: "Salt",
//           qty: 0.001, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 42.93,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-10222",
//           ingredId: 666,
//           ingredName: "0",
//           qty: 0.173, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//         {
//           uuid: "888-10333",
//           ingredId: 666,
//           ingredName: "0",
//           qty: 0, // QUANTITY Management : Start
//           // For Pro Mode
//           qty_estimated_from_home: 10000,
//           qty_estimated_confidence: 0.7,
//           // For Home Mode
//           home_qty_frac_numerator: 1,
//           home_qty_frac_denominator: 1,
//           home_qty: 1,
//           home_qty_type: "",
//           // QUANTITY Management : End
//           order: 2,
//           type: "ingredient",
//           instruction: "dice",
//           dietClassification: "animal_product",
//           stepInstruction: "",
//           supplier: "Acme",
//           unitType: "weight",
//           costPer1000: 66.66,
//           rationalisedRecipe: "",
//           needsPrep: false,
//           isSalt: false,
//           isSaltInWater: false,
//           isOil: false,
//           oilPurpose: "thin_coating",
//           subRecipeId: null,
//           FQscore: { positive: 0, negative: 0, neutral: 0, overall: 0, positiveTxt: "", negativeTxt: "", neutralTxt: "", overallTxt: "" },
//         },
//       ],
//     },
//   ],
// };
